<h1>Congratulations!</h1>

<!-- 
<p>You're now flying with Phalcon. Great things are about to happen!</p>

<p>This page is located at <code>views/index/index.phtml</code></p>

<h1>Lista de Ejercicios</h1>
<table>
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Grupo muscular</th>
    </tr>
    <?php foreach ($exercises as $exercise) { ?>
    <tr>
        <td><?= $exercise->id ?></td>
        <td><?= $exercise->name ?></td>
        <td>$<?= $exercise->muscle_group ?></td>
    </tr>
    <?php } ?>
</table> -->
